services:
  database-johnny:
    image: mongo:4.4
    container_name: Nightscout-Db-Johnny
    volumes:
      - /volume1/docker/mongodb-data-johnny:/data/db:cached

  nightscout-johnny:
    image: 'nightscout/cgm-remote-monitor:latest_dev'
    container_name: Nightscout-Johnny
    depends_on:
        - database
    ports:
      - '1337:1337'
    environment:
      - ALARM_URGENT_HIGH=off
      - ALARM_HIGH=off
      - ALARM_LOW=off
      - ALARM_TIMEAGO_WARN=off
      - ALARM_TIMEAGO_URGENT=off
      - ALARM_URGENT_LOW=off
      - API_SECRET=myapisecret
      - AUTH_DEFAULT_ROLES=denied
      - BASAL_RENDER=icicle
      - BRIDGE_PASSWORD=mybridgepassword
      - BRIDGE_SERVER=EU
      - BRIDGE_USER_NAME=mybridgeusername
      - CUSTOM_TITLE=Johnny's Nightscout
      - DEVICESTATUS_ADVANCED=true
      - DISPLAY_UNITS=mmol
      - ENABLE=bridge careportal basal dbsize rawbg iob maker cob bwp cage iage sage boluscalc pushover treatmentnotify loop pump profile food openaps bage alexa override speech cors
      - INSECURE_USE_HTTP=true
      - LANGUAGE=fr
      - LOOP_APNS_KEY=
       -----BEGIN PRIVATE KEY-----
       
       ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ22Ys7mCQ9x4I
       
       ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZfYNJz3IC2Vfj
       
       ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZb5dBysUjs87t
       
       px56uZHQ
       
       -----END PRIVATE KEY-----
      - LOOP_APNS_KEY_ID=myapnskeyid
      - LOOP_DEVELOPER_TEAM_ID=mydeveloperteamid
      - LOOP_ENABLE_ALERTS=true
      - NIGHT_MODE=off
      - MONGO_CONNECTION=mongodb://database-johnny:27017/nightscout
      - SHOW_FORECAST=loop
      - SHOW_PLUGINS=careportal boluscalc food iob cob basal pump loop bridge
      - TIME_FORMAT=24
      - THEME=colors
      - VIRTUAL_HOST=johnnysnightscout.duckdns.org
    links:
      - database-johnny

  database-sophia:
    image: mongo:4.4
    container_name: Nightscout-Db-Sophia
    volumes:
      - /volume1/docker/mongodb-data-sophia:/data/db:cached

  nightscout-sophia:
    image: 'nightscout/cgm-remote-monitor:latest_dev'
    container_name: Nightscout-Sophia
    depends_on:
        - database
    ports:
      - '1337:1337'
    environment:
      - ALARM_URGENT_HIGH=off
      - ALARM_HIGH=off
      - ALARM_LOW=off
      - ALARM_TIMEAGO_WARN=off
      - ALARM_TIMEAGO_URGENT=off
      - ALARM_URGENT_LOW=off
      - API_SECRET=myapisecret
      - AUTH_DEFAULT_ROLES=denied
      - BASAL_RENDER=icicle
      - BRIDGE_PASSWORD=mybridgepassword
      - BRIDGE_SERVER=EU
      - BRIDGE_USER_NAME=mybridgeusername
      - CUSTOM_TITLE=Sophia's Nightscout
      - DEVICESTATUS_ADVANCED=true
      - DISPLAY_UNITS=mmol
      - ENABLE=bridge careportal basal dbsize rawbg iob maker cob bwp cage iage sage boluscalc pushover treatmentnotify loop pump profile food openaps bage alexa override speech cors
      - INSECURE_USE_HTTP=true
      - LANGUAGE=fr
      - LOOP_APNS_KEY=
       -----BEGIN PRIVATE KEY-----
       
       ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ22Ys7mCQ9x4I
       
       ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZfYNJz3IC2Vfj
       
       ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZb5dBysUjs87t
       
       px56uZHQ
       
       -----END PRIVATE KEY-----
      - LOOP_APNS_KEY_ID=myapnskeyid
      - LOOP_DEVELOPER_TEAM_ID=mydeveloperteamid
      - LOOP_ENABLE_ALERTS=true
      - NIGHT_MODE=off
      - MONGO_CONNECTION=mongodb://database-sophia:27017/nightscout
      - SHOW_FORECAST=loop
      - SHOW_PLUGINS=careportal boluscalc food iob cob basal pump loop bridge
      - TIME_FORMAT=24
      - THEME=colors
      - VIRTUAL_HOST=sophiasnightscout.duckdns.org
    links:
      - database-sophia